### ISSUE TITLE
文件进行探测指纹发现卡住一直停留界面

### ISSUE THREAD

**Issue by rechallage** [qi4L/qscan#8]
![image](https://github.com/user-attachments/assets/f1f74e5f-0b3c-4230-8623-47d70f2c625b)
其中1.txt就这一个IP:port，明明扫完却未结束进程
![image](https://github.com/user-attachments/assets/a26cc8f1-95f3-41df-bf47-ae36107f69c1)

**Comment by qi4L** [comment]
格式错了吧，端口的话用-p去指定

**Comment by qi4L** [comment]
是有问题，我找找

**Comment by qi4L** [comment]
BUG解决了
端口指定要用-p
