### ISSUE TITLE
【讨论】可以增加进度显示，外网扫描导致网络堵塞

### ISSUE THREAD

**Issue by ailx1101** [qi4L/qscan#9]
没有进度显示不知道什么时候结束，总以为是卡住了，不知道大佬可否增加一下

**Comment by qi4L** [comment]
其实这个就是在告诉你还有多少在跑的意思了
warn := fmt.Sprintf("当前存活协程数：IP：%d 个，Port：%d 个，URL：%d 个，Hydra：%d 个", nIP, nPort, nURL, nHydra)

**Comment by qi4L** [comment]
如果这个都打印为0
warn := fmt.Sprintf("当前存活协程数：IP：%d 个，Port：%d 个，URL：%d 个，Hydra：%d 个", nIP, nPort, nURL, nHydra)
就说明只剩还在使用的协程还没走完了

**Comment by qi4L** [comment]
可以加最后还没走完的协程进度

**Comment by ailx1101** [comment]
> 可以加最后还没走完的协程进度

还有一个问题。如果我要扫描1-65535端口。使用默认线程。路由器显示连接数能达到4w多个连接。直接导致其他设备无法正常上网，而且就算指定了线程也还是会造成网络堵塞

**Comment by qi4L** [comment]
应该不是qscan的问题，因为我做B段扫描的时候，还是限制在协程数理内的

**Comment by ailx1101** [comment]
> 应该不是qscan的问题，因为我做B段扫描的时候，还是限制在协程数理内的

举个例子: 我在测试外网ip时 会出现网络堵塞情况
./qscan.exe -p 1-65535 -t 46.3.xx.xx --threads 2000
![Snipaste_2024-10-21_21-00-15](https://github.com/user-attachments/assets/42189227-3aae-4bcc-bbcd-6f1cfd0305bf)
![Snipaste_2024-10-21_21-00-42](https://github.com/user-attachments/assets/75dca5e8-2e1a-4b0c-b6ce-f098a8a10a37)

**Comment by qi4L** [comment]
你的问题，就是答案
